name: npm-publish-sample-project

on:
  push:
    branches:
      - main
    paths:
      - 'sample-npm-package-fujimori/**'

  # 手動実行
  workflow_dispatch:

defaults:
  run:
    working-directory: ./sample-npm-package-fujimori

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - run: npm ci

      - name: Can Publish package
        run: |
          if npx can-npm-publish --verbose; then
            echo "CAN_PUBLISH=true" >> $GITHUB_ENV
          else
            echo "CAN_PUBLISH=false" >> $GITHUB_ENV
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Bump version and commit
        if: env.CAN_PUBLISH == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # npm versionでバージョンをインクリメント
          npm version patch --no-git-tag-version

          # 変更をコミットしてプッシュ
          git add package.json package-lock.json
          git commit -m "version auto increment"
          git push origin main

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
